// Code generated by protobuf.gen. DO NOT EDIT.
module main

import grpc

pub struct KVDClient {
pub mut:
	c grpc.Client
}

pub fn (mut x KVDClient) get(req GetRequest) !GetResponse {
	resp := x.c.unary('/kvd.KVD/Get', req.encode())!
	return GetResponse.decode(resp)!
}

pub fn (mut x KVDClient) put(req PutRequest) !PutResponse {
	resp := x.c.unary('/kvd.KVD/Put', req.encode())!
	return PutResponse.decode(resp)!
}

pub fn (mut x KVDClient) delete(req DeleteRequest) !DeleteResponse {
	resp := x.c.unary('/kvd.KVD/Delete', req.encode())!
	return DeleteResponse.decode(resp)!
}

pub fn (mut x KVDClient) range(req RangeRequest) !RangeResponse {
	resp := x.c.unary('/kvd.KVD/Range', req.encode())!
	return RangeResponse.decode(resp)!
}

pub interface KVDHandler {
mut:
	get(req GetRequest) !GetResponse
	put(req PutRequest) !PutResponse
	delete(req DeleteRequest) !DeleteResponse
	range(req RangeRequest) !RangeResponse
}

pub struct KVDService {
pub mut:
	h KVDHandler
}

pub fn (mut s KVDService) call(path string, codec grpc.Codec, body []u8) !([]u8, bool) {
	match path {
		'/kvd.KVD/Get' {
			req := if codec == .json {
				GetRequest.from_json(body.bytestr())!
			} else {
				GetRequest.decode(body)!
			}
			resp := s.h.get(req)!
			out := if codec == .json {
				resp.json().bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/kvd.KVD/Put' {
			req := if codec == .json {
				PutRequest.from_json(body.bytestr())!
			} else {
				PutRequest.decode(body)!
			}
			resp := s.h.put(req)!
			out := if codec == .json {
				resp.json().bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/kvd.KVD/Delete' {
			req := if codec == .json {
				DeleteRequest.from_json(body.bytestr())!
			} else {
				DeleteRequest.decode(body)!
			}
			resp := s.h.delete(req)!
			out := if codec == .json {
				resp.json().bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/kvd.KVD/Range' {
			req := if codec == .json {
				RangeRequest.from_json(body.bytestr())!
			} else {
				RangeRequest.decode(body)!
			}
			resp := s.h.range(req)!
			out := if codec == .json {
				resp.json().bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		else {
			return []u8{}, false
		}
	}
}
