// Code generated by protobuf.gen. DO NOT EDIT.
module main

import json2
import protobuf

pub struct GetRequest {
pub mut:
	key        []u8
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &GetRequest) encoded_size() int {
	mut n := 0
	if m.key.len > 0 {
		n += protobuf.len_field_len(1, m.key.len)
	}
	return n + m.pb_unknown.len
}

pub fn (m &GetRequest) encode_to(mut e protobuf.Encoder) {
	if m.key.len > 0 {
		e.write_bytes_field(1, m.key)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &GetRequest) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn GetRequest.decode(buf []u8) !GetRequest {
	mut m := GetRequest{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.key = d.read_bytes()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &GetRequest) json() !string {
	return m.json_value()!.json_str()
}

pub fn GetRequest.from_json(s string) !GetRequest {
	return GetRequest.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &GetRequest) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.key.len > 0 {
		o['key'] = protobuf.json_b64(m.key)
	}
	return json2.Any(o)
}

pub fn GetRequest.from_json_value(a json2.Any) !GetRequest {
	obj := protobuf.json_object(a)!
	mut m := GetRequest{}
	for jk, jv in obj {
		match jk {
			'key' {
				if jv !is json2.Null {
					m.key = protobuf.json_bytesv(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct GetResponse {
pub mut:
	value      []u8
	found      bool
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &GetResponse) encoded_size() int {
	mut n := 0
	if m.value.len > 0 {
		n += protobuf.len_field_len(1, m.value.len)
	}
	if m.found {
		n += protobuf.tag_len(2) + 1
	}
	return n + m.pb_unknown.len
}

pub fn (m &GetResponse) encode_to(mut e protobuf.Encoder) {
	if m.value.len > 0 {
		e.write_bytes_field(1, m.value)
	}
	if m.found {
		e.write_bool_field(2, m.found)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &GetResponse) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn GetResponse.decode(buf []u8) !GetResponse {
	mut m := GetResponse{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.value = d.read_bytes()!
			}
			2 {
				m.found = d.read_bool()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &GetResponse) json() !string {
	return m.json_value()!.json_str()
}

pub fn GetResponse.from_json(s string) !GetResponse {
	return GetResponse.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &GetResponse) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.value.len > 0 {
		o['value'] = protobuf.json_b64(m.value)
	}
	if m.found {
		o['found'] = json2.Any(m.found)
	}
	return json2.Any(o)
}

pub fn GetResponse.from_json_value(a json2.Any) !GetResponse {
	obj := protobuf.json_object(a)!
	mut m := GetResponse{}
	for jk, jv in obj {
		match jk {
			'value' {
				if jv !is json2.Null {
					m.value = protobuf.json_bytesv(jv)!
				}
			}
			'found' {
				if jv !is json2.Null {
					m.found = protobuf.json_boolv(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct PutRequest {
pub mut:
	key        []u8
	value      []u8
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &PutRequest) encoded_size() int {
	mut n := 0
	if m.key.len > 0 {
		n += protobuf.len_field_len(1, m.key.len)
	}
	if m.value.len > 0 {
		n += protobuf.len_field_len(2, m.value.len)
	}
	return n + m.pb_unknown.len
}

pub fn (m &PutRequest) encode_to(mut e protobuf.Encoder) {
	if m.key.len > 0 {
		e.write_bytes_field(1, m.key)
	}
	if m.value.len > 0 {
		e.write_bytes_field(2, m.value)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &PutRequest) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn PutRequest.decode(buf []u8) !PutRequest {
	mut m := PutRequest{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.key = d.read_bytes()!
			}
			2 {
				m.value = d.read_bytes()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &PutRequest) json() !string {
	return m.json_value()!.json_str()
}

pub fn PutRequest.from_json(s string) !PutRequest {
	return PutRequest.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &PutRequest) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.key.len > 0 {
		o['key'] = protobuf.json_b64(m.key)
	}
	if m.value.len > 0 {
		o['value'] = protobuf.json_b64(m.value)
	}
	return json2.Any(o)
}

pub fn PutRequest.from_json_value(a json2.Any) !PutRequest {
	obj := protobuf.json_object(a)!
	mut m := PutRequest{}
	for jk, jv in obj {
		match jk {
			'key' {
				if jv !is json2.Null {
					m.key = protobuf.json_bytesv(jv)!
				}
			}
			'value' {
				if jv !is json2.Null {
					m.value = protobuf.json_bytesv(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct PutResponse {
pub mut:
	replaced   bool
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &PutResponse) encoded_size() int {
	mut n := 0
	if m.replaced {
		n += protobuf.tag_len(1) + 1
	}
	return n + m.pb_unknown.len
}

pub fn (m &PutResponse) encode_to(mut e protobuf.Encoder) {
	if m.replaced {
		e.write_bool_field(1, m.replaced)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &PutResponse) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn PutResponse.decode(buf []u8) !PutResponse {
	mut m := PutResponse{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.replaced = d.read_bool()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &PutResponse) json() !string {
	return m.json_value()!.json_str()
}

pub fn PutResponse.from_json(s string) !PutResponse {
	return PutResponse.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &PutResponse) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.replaced {
		o['replaced'] = json2.Any(m.replaced)
	}
	return json2.Any(o)
}

pub fn PutResponse.from_json_value(a json2.Any) !PutResponse {
	obj := protobuf.json_object(a)!
	mut m := PutResponse{}
	for jk, jv in obj {
		match jk {
			'replaced' {
				if jv !is json2.Null {
					m.replaced = protobuf.json_boolv(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct DeleteRequest {
pub mut:
	key        []u8
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &DeleteRequest) encoded_size() int {
	mut n := 0
	if m.key.len > 0 {
		n += protobuf.len_field_len(1, m.key.len)
	}
	return n + m.pb_unknown.len
}

pub fn (m &DeleteRequest) encode_to(mut e protobuf.Encoder) {
	if m.key.len > 0 {
		e.write_bytes_field(1, m.key)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &DeleteRequest) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn DeleteRequest.decode(buf []u8) !DeleteRequest {
	mut m := DeleteRequest{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.key = d.read_bytes()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &DeleteRequest) json() !string {
	return m.json_value()!.json_str()
}

pub fn DeleteRequest.from_json(s string) !DeleteRequest {
	return DeleteRequest.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &DeleteRequest) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.key.len > 0 {
		o['key'] = protobuf.json_b64(m.key)
	}
	return json2.Any(o)
}

pub fn DeleteRequest.from_json_value(a json2.Any) !DeleteRequest {
	obj := protobuf.json_object(a)!
	mut m := DeleteRequest{}
	for jk, jv in obj {
		match jk {
			'key' {
				if jv !is json2.Null {
					m.key = protobuf.json_bytesv(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct DeleteResponse {
pub mut:
	existed    bool
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &DeleteResponse) encoded_size() int {
	mut n := 0
	if m.existed {
		n += protobuf.tag_len(1) + 1
	}
	return n + m.pb_unknown.len
}

pub fn (m &DeleteResponse) encode_to(mut e protobuf.Encoder) {
	if m.existed {
		e.write_bool_field(1, m.existed)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &DeleteResponse) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn DeleteResponse.decode(buf []u8) !DeleteResponse {
	mut m := DeleteResponse{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.existed = d.read_bool()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &DeleteResponse) json() !string {
	return m.json_value()!.json_str()
}

pub fn DeleteResponse.from_json(s string) !DeleteResponse {
	return DeleteResponse.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &DeleteResponse) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.existed {
		o['existed'] = json2.Any(m.existed)
	}
	return json2.Any(o)
}

pub fn DeleteResponse.from_json_value(a json2.Any) !DeleteResponse {
	obj := protobuf.json_object(a)!
	mut m := DeleteResponse{}
	for jk, jv in obj {
		match jk {
			'existed' {
				if jv !is json2.Null {
					m.existed = protobuf.json_boolv(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct RangeRequest {
pub mut:
	start      []u8
	end        []u8
	limit      int
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &RangeRequest) encoded_size() int {
	mut n := 0
	if m.start.len > 0 {
		n += protobuf.len_field_len(1, m.start.len)
	}
	if m.end.len > 0 {
		n += protobuf.len_field_len(2, m.end.len)
	}
	if m.limit != 0 {
		n += protobuf.tag_len(3) + protobuf.varint_len(u64(i64(m.limit)))
	}
	return n + m.pb_unknown.len
}

pub fn (m &RangeRequest) encode_to(mut e protobuf.Encoder) {
	if m.start.len > 0 {
		e.write_bytes_field(1, m.start)
	}
	if m.end.len > 0 {
		e.write_bytes_field(2, m.end)
	}
	if m.limit != 0 {
		e.write_int32_field(3, m.limit)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &RangeRequest) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn RangeRequest.decode(buf []u8) !RangeRequest {
	mut m := RangeRequest{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.start = d.read_bytes()!
			}
			2 {
				m.end = d.read_bytes()!
			}
			3 {
				m.limit = d.read_int32()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &RangeRequest) json() !string {
	return m.json_value()!.json_str()
}

pub fn RangeRequest.from_json(s string) !RangeRequest {
	return RangeRequest.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &RangeRequest) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.start.len > 0 {
		o['start'] = protobuf.json_b64(m.start)
	}
	if m.end.len > 0 {
		o['end'] = protobuf.json_b64(m.end)
	}
	if m.limit != 0 {
		o['limit'] = json2.Any(i64(m.limit))
	}
	return json2.Any(o)
}

pub fn RangeRequest.from_json_value(a json2.Any) !RangeRequest {
	obj := protobuf.json_object(a)!
	mut m := RangeRequest{}
	for jk, jv in obj {
		match jk {
			'start' {
				if jv !is json2.Null {
					m.start = protobuf.json_bytesv(jv)!
				}
			}
			'end' {
				if jv !is json2.Null {
					m.end = protobuf.json_bytesv(jv)!
				}
			}
			'limit' {
				if jv !is json2.Null {
					m.limit = protobuf.json_int32v(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct KeyValue {
pub mut:
	key        []u8
	value      []u8
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &KeyValue) encoded_size() int {
	mut n := 0
	if m.key.len > 0 {
		n += protobuf.len_field_len(1, m.key.len)
	}
	if m.value.len > 0 {
		n += protobuf.len_field_len(2, m.value.len)
	}
	return n + m.pb_unknown.len
}

pub fn (m &KeyValue) encode_to(mut e protobuf.Encoder) {
	if m.key.len > 0 {
		e.write_bytes_field(1, m.key)
	}
	if m.value.len > 0 {
		e.write_bytes_field(2, m.value)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &KeyValue) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn KeyValue.decode(buf []u8) !KeyValue {
	mut m := KeyValue{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.key = d.read_bytes()!
			}
			2 {
				m.value = d.read_bytes()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &KeyValue) json() !string {
	return m.json_value()!.json_str()
}

pub fn KeyValue.from_json(s string) !KeyValue {
	return KeyValue.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &KeyValue) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.key.len > 0 {
		o['key'] = protobuf.json_b64(m.key)
	}
	if m.value.len > 0 {
		o['value'] = protobuf.json_b64(m.value)
	}
	return json2.Any(o)
}

pub fn KeyValue.from_json_value(a json2.Any) !KeyValue {
	obj := protobuf.json_object(a)!
	mut m := KeyValue{}
	for jk, jv in obj {
		match jk {
			'key' {
				if jv !is json2.Null {
					m.key = protobuf.json_bytesv(jv)!
				}
			}
			'value' {
				if jv !is json2.Null {
					m.value = protobuf.json_bytesv(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct RangeResponse {
pub mut:
	kvs        []KeyValue
	more       bool
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &RangeResponse) encoded_size() int {
	mut n := 0
	for v in m.kvs {
		n += protobuf.len_field_len(1, v.encoded_size())
	}
	if m.more {
		n += protobuf.tag_len(2) + 1
	}
	return n + m.pb_unknown.len
}

pub fn (m &RangeResponse) encode_to(mut e protobuf.Encoder) {
	for v in m.kvs {
		e.write_tag(1, .len_delim)
		e.write_varint(u64(v.encoded_size()))
		v.encode_to(mut e)
	}
	if m.more {
		e.write_bool_field(2, m.more)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &RangeResponse) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn RangeResponse.decode(buf []u8) !RangeResponse {
	mut m := RangeResponse{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.kvs << KeyValue.decode(d.read_view()!)!
			}
			2 {
				m.more = d.read_bool()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &RangeResponse) json() !string {
	return m.json_value()!.json_str()
}

pub fn RangeResponse.from_json(s string) !RangeResponse {
	return RangeResponse.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &RangeResponse) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.kvs.len > 0 {
		mut kvs_a := []json2.Any{cap: m.kvs.len}
		for v in m.kvs {
			kvs_a << v.json_value()!
		}
		o['kvs'] = json2.Any(kvs_a)
	}
	if m.more {
		o['more'] = json2.Any(m.more)
	}
	return json2.Any(o)
}

pub fn RangeResponse.from_json_value(a json2.Any) !RangeResponse {
	obj := protobuf.json_object(a)!
	mut m := RangeResponse{}
	for jk, jv in obj {
		match jk {
			'kvs' {
				if jv !is json2.Null {
					for it in protobuf.json_array(jv)! {
						m.kvs << KeyValue.from_json_value(it)!
					}
				}
			}
			'more' {
				if jv !is json2.Null {
					m.more = protobuf.json_boolv(jv)!
				}
			}
			else {}
		}
	}
	return m
}
