// Code generated by protobuf.gen. DO NOT EDIT.
module main

import grpc

pub struct KVDClient {
pub mut:
	c grpc.Client
}

pub fn (mut x KVDClient) get(req GetRequest, opts ...grpc.CallOption) !grpc.Reply[GetResponse] {
	raw := x.c.unary('/kvd.KVD/Get', req.encode(), ...opts)!
	return grpc.Reply[GetResponse]{
		msg:      GetResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub fn (mut x KVDClient) put(req PutRequest, opts ...grpc.CallOption) !grpc.Reply[PutResponse] {
	raw := x.c.unary('/kvd.KVD/Put', req.encode(), ...opts)!
	return grpc.Reply[PutResponse]{
		msg:      PutResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub fn (mut x KVDClient) delete(req DeleteRequest, opts ...grpc.CallOption) !grpc.Reply[DeleteResponse] {
	raw := x.c.unary('/kvd.KVD/Delete', req.encode(), ...opts)!
	return grpc.Reply[DeleteResponse]{
		msg:      DeleteResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub fn (mut x KVDClient) range(req RangeRequest, opts ...grpc.CallOption) !grpc.Reply[RangeResponse] {
	raw := x.c.unary('/kvd.KVD/Range', req.encode(), ...opts)!
	return grpc.Reply[RangeResponse]{
		msg:      RangeResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub interface KVDHandler {
mut:
	get(mut ctx grpc.ServerContext, req GetRequest) !GetResponse
	put(mut ctx grpc.ServerContext, req PutRequest) !PutResponse
	delete(mut ctx grpc.ServerContext, req DeleteRequest) !DeleteResponse
	range(mut ctx grpc.ServerContext, req RangeRequest) !RangeResponse
}

pub struct KVDService {
pub mut:
	h KVDHandler
}

pub fn (mut s KVDService) call(path string, codec grpc.Codec, body []u8, mut ctx grpc.ServerContext) !([]u8, bool) {
	match path {
		'/kvd.KVD/Get' {
			req := if codec == .json {
				GetRequest.from_json(body.bytestr())!
			} else {
				GetRequest.decode(body)!
			}
			resp := s.h.get(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/kvd.KVD/Put' {
			req := if codec == .json {
				PutRequest.from_json(body.bytestr())!
			} else {
				PutRequest.decode(body)!
			}
			resp := s.h.put(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/kvd.KVD/Delete' {
			req := if codec == .json {
				DeleteRequest.from_json(body.bytestr())!
			} else {
				DeleteRequest.decode(body)!
			}
			resp := s.h.delete(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/kvd.KVD/Range' {
			req := if codec == .json {
				RangeRequest.from_json(body.bytestr())!
			} else {
				RangeRequest.decode(body)!
			}
			resp := s.h.range(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		else {
			return []u8{}, false
		}
	}
}
