// kvd: etcd-lite — a persistent KV service. vlang/leveldb storage, the
// Connect protocol on the wire, everything between generated by vpbgen.
//
//   v run examples/kvd [data-dir] [addr]
//   curl -X POST localhost:8181/kvd.KVD/Put -H 'content-type: application/json' \
//        -d '{"key":"aGk=","value":"d29ybGQ="}'
module main

import os
import grpc
import leveldb

const default_range_limit = 100
const max_range_limit = 1000

struct Store {
mut:
	db &leveldb.DB
}

fn (mut s Store) get(req GetRequest) !GetResponse {
	if v := s.db.get(req.key, leveldb.ReadOptions{}) {
		return GetResponse{
			value: v
			found: true
		}
	}
	return GetResponse{}
}

fn (mut s Store) put(req PutRequest) !PutResponse {
	if req.key.len == 0 {
		return grpc.StatusError{
			status: grpc.Status{
				code:    .invalid_argument
				message: 'key must not be empty'
			}
		}
	}
	replaced := s.db.has(req.key, leveldb.ReadOptions{})
	s.db.put(req.key, req.value, leveldb.WriteOptions{})!
	return PutResponse{
		replaced: replaced
	}
}

fn (mut s Store) delete(req DeleteRequest) !DeleteResponse {
	existed := s.db.has(req.key, leveldb.ReadOptions{})
	if existed {
		s.db.delete(req.key, leveldb.WriteOptions{})!
	}
	return DeleteResponse{
		existed: existed
	}
}

// bytewise lexicographic, the same order leveldb stores keys in
fn lt(a []u8, b []u8) bool {
	mut i := 0
	for i < a.len && i < b.len {
		if a[i] != b[i] {
			return a[i] < b[i]
		}
		i++
	}
	return a.len < b.len
}

fn (mut s Store) range(req RangeRequest) !RangeResponse {
	mut limit := int(req.limit)
	if limit <= 0 {
		limit = default_range_limit
	}
	if limit > max_range_limit {
		limit = max_range_limit
	}
	mut it := s.db.new_iterator(leveldb.ReadOptions{})!
	mut ok := if req.start.len > 0 { it.seek(req.start) } else { it.first() }
	mut resp := RangeResponse{}
	for ok && it.valid() {
		k := it.key()
		if req.end.len > 0 && !lt(k, req.end) {
			break
		}
		if resp.kvs.len >= limit {
			resp.more = true
			break
		}
		resp.kvs << KeyValue{
			key:   k.clone()
			value: it.value().clone()
		}
		ok = it.next()
	}
	return resp
}

fn main() {
	dir := if os.args.len > 1 { os.args[1] } else { 'kvd.db' }
	addr := if os.args.len > 2 { os.args[2] } else { ':8181' }
	mut db := leveldb.open(dir, leveldb.Options{}) or { panic('cannot open ${dir}: ${err}') }
	defer {
		db.close() or {}
	}
	mut srv := grpc.ConnectServer{
		addr: addr
	}
	srv.mount(KVDService{
		h: Store{
			db: db
		}
	})
	println('kvd serving ${dir} on ${addr}')
	srv.listen_and_serve() or { panic(err) }
}
