// Code generated by protobuf.gen. DO NOT EDIT.
module main

import grpc

pub struct RegistryClient {
pub mut:
	c grpc.Client
}

pub fn (mut x RegistryClient) put(req PutRequest) !PutResponse {
	resp := x.c.unary('/registry.Registry/Put', req.encode())!
	return PutResponse.decode(resp)!
}

pub fn (mut x RegistryClient) get(req GetRequest) !GetResponse {
	resp := x.c.unary('/registry.Registry/Get', req.encode())!
	return GetResponse.decode(resp)!
}

pub interface RegistryHandler {
mut:
	put(req PutRequest) !PutResponse
	get(req GetRequest) !GetResponse
}

pub struct RegistryService {
pub mut:
	h RegistryHandler
}

pub fn (mut s RegistryService) call(path string, codec grpc.Codec, body []u8) !([]u8, bool) {
	match path {
		'/registry.Registry/Put' {
			req := if codec == .json {
				PutRequest.from_json(body.bytestr())!
			} else {
				PutRequest.decode(body)!
			}
			resp := s.h.put(req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/registry.Registry/Get' {
			req := if codec == .json {
				GetRequest.from_json(body.bytestr())!
			} else {
				GetRequest.decode(body)!
			}
			resp := s.h.get(req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		else {
			return []u8{}, false
		}
	}
}
