// Code generated by protobuf.gen. DO NOT EDIT.
module main

import json2
import protobuf
import time

pub enum Health {
	health_unknown  = 0
	health_passing  = 1
	health_critical = 2
}

fn health_to_json(v Health) json2.Any {
	return match int(v) {
		0 { json2.Any('HEALTH_UNKNOWN') }
		1 { json2.Any('HEALTH_PASSING') }
		2 { json2.Any('HEALTH_CRITICAL') }
		else { json2.Any(i64(int(v))) }
	}
}

fn health_from_json(a json2.Any) !Health {
	if a is string {
		match a {
			'HEALTH_UNKNOWN' { return unsafe { Health(0) } }
			'HEALTH_PASSING' { return unsafe { Health(1) } }
			'HEALTH_OK' { return unsafe { Health(1) } }
			'HEALTH_CRITICAL' { return unsafe { Health(2) } }
			else { return error('protojson: unknown value `${a}` for Health') }
		}
	}
	return unsafe { Health(int(protobuf.json_intv(a)!)) }
}

pub struct Node {
pub mut:
	name       string
	health     Health
	meta       map[string]string
	registered ?GoogleProtobuf_Timestamp
	ttl        ?GoogleProtobuf_Duration
	detail     ?GoogleProtobuf_Any
	children   []Node
	leader     ?&Node
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (a Node) == (b Node) bool {
	return a.encode() == b.encode()
}

pub fn (m &Node) encoded_size() int {
	mut n := 0
	if m.name != '' {
		n += protobuf.len_field_len(1, m.name.len)
	}
	if int(m.health) != 0 {
		n += protobuf.tag_len(2) + protobuf.varint_len(u64(i64(int(m.health))))
	}
	for k, v in m.meta {
		n += protobuf.len_field_len(3, protobuf.len_field_len(1, k.len) +
			protobuf.len_field_len(2, v.len))
	}
	if registered := m.registered {
		n += protobuf.len_field_len(4, registered.encoded_size())
	}
	if ttl := m.ttl {
		n += protobuf.len_field_len(5, ttl.encoded_size())
	}
	if detail := m.detail {
		n += protobuf.len_field_len(6, detail.encoded_size())
	}
	for v in m.children {
		n += protobuf.len_field_len(7, v.encoded_size())
	}
	if leader := m.leader {
		n += protobuf.len_field_len(8, leader.encoded_size())
	}
	return n + m.pb_unknown.len
}

pub fn (m &Node) encode_to(mut e protobuf.Encoder) {
	if m.name != '' {
		e.write_string_field(1, m.name)
	}
	if int(m.health) != 0 {
		e.write_int32_field(2, int(m.health))
	}
	if m.meta.len > 0 {
		mut meta_keys := m.meta.keys()
		meta_keys.sort()
		for k in meta_keys {
			v := m.meta[k]
			e.write_tag(3, .len_delim)
			e.write_varint(u64(protobuf.len_field_len(1, k.len) + protobuf.len_field_len(2, v.len)))
			e.write_string_field(1, k)
			e.write_string_field(2, v)
		}
	}
	if registered := m.registered {
		e.write_tag(4, .len_delim)
		e.write_varint(u64(registered.encoded_size()))
		registered.encode_to(mut e)
	}
	if ttl := m.ttl {
		e.write_tag(5, .len_delim)
		e.write_varint(u64(ttl.encoded_size()))
		ttl.encode_to(mut e)
	}
	if detail := m.detail {
		e.write_tag(6, .len_delim)
		e.write_varint(u64(detail.encoded_size()))
		detail.encode_to(mut e)
	}
	for v in m.children {
		e.write_tag(7, .len_delim)
		e.write_varint(u64(v.encoded_size()))
		v.encode_to(mut e)
	}
	if leader := m.leader {
		e.write_tag(8, .len_delim)
		e.write_varint(u64(leader.encoded_size()))
		leader.encode_to(mut e)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &Node) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn Node.decode(buf []u8) !Node {
	mut m := Node{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.name = d.read_string()!
			}
			2 {
				m.health = unsafe { Health(d.read_int32()!) }
			}
			3 {
				mut sub := protobuf.Decoder{
					buf: d.read_view()!
				}
				mut mk := ''
				mut mv := ''
				for sub.more() {
					mf, mw := sub.read_tag()!
					match mf {
						1 { mk = sub.read_string()! }
						2 { mv = sub.read_string()! }
						else { sub.skip(mw)! }
					}
				}
				m.meta[mk] = mv
			}
			4 {
				mv_registered := d.read_view()!
				mut mb_registered := []u8{}
				if old := m.registered {
					mb_registered = old.encode()
				}
				mb_registered << mv_registered
				m.registered = GoogleProtobuf_Timestamp.decode(mb_registered)!
			}
			5 {
				mv_ttl := d.read_view()!
				mut mb_ttl := []u8{}
				if old := m.ttl {
					mb_ttl = old.encode()
				}
				mb_ttl << mv_ttl
				m.ttl = GoogleProtobuf_Duration.decode(mb_ttl)!
			}
			6 {
				mv_detail := d.read_view()!
				mut mb_detail := []u8{}
				if old := m.detail {
					mb_detail = old.encode()
				}
				mb_detail << mv_detail
				m.detail = GoogleProtobuf_Any.decode(mb_detail)!
			}
			7 {
				m.children << Node.decode(d.read_view()!)!
			}
			8 {
				mv_leader := d.read_view()!
				mut mb_leader := []u8{}
				if old := m.leader {
					mb_leader = old.encode()
				}
				mb_leader << mv_leader
				box_leader := Node.decode(mb_leader)!
				m.leader = &box_leader
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &Node) to_any() GoogleProtobuf_Any {
	return GoogleProtobuf_Any{
		type_url: 'type.googleapis.com/registry.Node'
		value:    m.encode()
	}
}

pub fn Node.from_any(a GoogleProtobuf_Any) !Node {
	got := a.type_url.all_after_last('/')
	if got != 'registry.Node' {
		return error('protobuf: Any holds `${got}`, not `registry.Node`')
	}
	return Node.decode(a.value)!
}

pub fn (m &Node) json() !string {
	return m.json_value()!.json_str()
}

pub fn Node.from_json(s string) !Node {
	return Node.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &Node) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.name != '' {
		o['name'] = json2.Any(m.name)
	}
	if int(m.health) != 0 {
		o['health'] = health_to_json(m.health)
	}
	if m.meta.len > 0 {
		mut meta_o := map[string]json2.Any{}
		mut meta_ks := m.meta.keys()
		meta_ks.sort()
		for k in meta_ks {
			v := m.meta[k]
			meta_o[k] = json2.Any(v)
		}
		o['meta'] = json2.Any(meta_o)
	}
	if registered := m.registered {
		o['registered'] = registered.json_value()!
	}
	if ttl := m.ttl {
		o['ttl'] = ttl.json_value()!
	}
	if detail := m.detail {
		o['detail'] = detail.json_value()!
	}
	if m.children.len > 0 {
		mut children_a := []json2.Any{cap: m.children.len}
		for v in m.children {
			children_a << v.json_value()!
		}
		o['children'] = json2.Any(children_a)
	}
	if leader := m.leader {
		o['leader'] = leader.json_value()!
	}
	return json2.Any(o)
}

pub fn Node.from_json_value(a json2.Any) !Node {
	obj := protobuf.json_object(a)!
	mut m := Node{}
	for jk, jv in obj {
		match jk {
			'name' {
				if jv !is json2.Null {
					m.name = protobuf.json_stringv(jv)!
				}
			}
			'health' {
				if jv !is json2.Null {
					m.health = health_from_json(jv)!
				}
			}
			'meta' {
				if jv !is json2.Null {
					for mk, mv in protobuf.json_object(jv)! {
						m.meta[mk] = protobuf.json_stringv(mv)!
					}
				}
			}
			'registered' {
				if jv !is json2.Null {
					m.registered = GoogleProtobuf_Timestamp.from_json_value(jv)!
				}
			}
			'ttl' {
				if jv !is json2.Null {
					m.ttl = GoogleProtobuf_Duration.from_json_value(jv)!
				}
			}
			'detail' {
				if jv !is json2.Null {
					m.detail = GoogleProtobuf_Any.from_json_value(jv)!
				}
			}
			'children' {
				if jv !is json2.Null {
					for it in protobuf.json_array(jv)! {
						m.children << Node.from_json_value(it)!
					}
				}
			}
			'leader' {
				if jv !is json2.Null {
					box_leader := Node.from_json_value(jv)!
					m.leader = &box_leader
				}
			}
			else {}
		}
	}
	return m
}

pub struct PutRequest {
pub mut:
	root       ?Node
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &PutRequest) encoded_size() int {
	mut n := 0
	if root := m.root {
		n += protobuf.len_field_len(1, root.encoded_size())
	}
	return n + m.pb_unknown.len
}

pub fn (m &PutRequest) encode_to(mut e protobuf.Encoder) {
	if root := m.root {
		e.write_tag(1, .len_delim)
		e.write_varint(u64(root.encoded_size()))
		root.encode_to(mut e)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &PutRequest) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn PutRequest.decode(buf []u8) !PutRequest {
	mut m := PutRequest{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				mv_root := d.read_view()!
				mut mb_root := []u8{}
				if old := m.root {
					mb_root = old.encode()
				}
				mb_root << mv_root
				m.root = Node.decode(mb_root)!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &PutRequest) to_any() GoogleProtobuf_Any {
	return GoogleProtobuf_Any{
		type_url: 'type.googleapis.com/registry.PutRequest'
		value:    m.encode()
	}
}

pub fn PutRequest.from_any(a GoogleProtobuf_Any) !PutRequest {
	got := a.type_url.all_after_last('/')
	if got != 'registry.PutRequest' {
		return error('protobuf: Any holds `${got}`, not `registry.PutRequest`')
	}
	return PutRequest.decode(a.value)!
}

pub fn (m &PutRequest) json() !string {
	return m.json_value()!.json_str()
}

pub fn PutRequest.from_json(s string) !PutRequest {
	return PutRequest.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &PutRequest) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if root := m.root {
		o['root'] = root.json_value()!
	}
	return json2.Any(o)
}

pub fn PutRequest.from_json_value(a json2.Any) !PutRequest {
	obj := protobuf.json_object(a)!
	mut m := PutRequest{}
	for jk, jv in obj {
		match jk {
			'root' {
				if jv !is json2.Null {
					m.root = Node.from_json_value(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct PutResponse {
pub mut:
	nodes      int
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &PutResponse) encoded_size() int {
	mut n := 0
	if m.nodes != 0 {
		n += protobuf.tag_len(1) + protobuf.varint_len(u64(i64(m.nodes)))
	}
	return n + m.pb_unknown.len
}

pub fn (m &PutResponse) encode_to(mut e protobuf.Encoder) {
	if m.nodes != 0 {
		e.write_int32_field(1, m.nodes)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &PutResponse) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn PutResponse.decode(buf []u8) !PutResponse {
	mut m := PutResponse{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.nodes = d.read_int32()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &PutResponse) to_any() GoogleProtobuf_Any {
	return GoogleProtobuf_Any{
		type_url: 'type.googleapis.com/registry.PutResponse'
		value:    m.encode()
	}
}

pub fn PutResponse.from_any(a GoogleProtobuf_Any) !PutResponse {
	got := a.type_url.all_after_last('/')
	if got != 'registry.PutResponse' {
		return error('protobuf: Any holds `${got}`, not `registry.PutResponse`')
	}
	return PutResponse.decode(a.value)!
}

pub fn (m &PutResponse) json() !string {
	return m.json_value()!.json_str()
}

pub fn PutResponse.from_json(s string) !PutResponse {
	return PutResponse.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &PutResponse) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.nodes != 0 {
		o['nodes'] = json2.Any(i64(m.nodes))
	}
	return json2.Any(o)
}

pub fn PutResponse.from_json_value(a json2.Any) !PutResponse {
	obj := protobuf.json_object(a)!
	mut m := PutResponse{}
	for jk, jv in obj {
		match jk {
			'nodes' {
				if jv !is json2.Null {
					m.nodes = protobuf.json_int32v(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct GetRequest {
pub mut:
	path       string
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &GetRequest) encoded_size() int {
	mut n := 0
	if m.path != '' {
		n += protobuf.len_field_len(1, m.path.len)
	}
	return n + m.pb_unknown.len
}

pub fn (m &GetRequest) encode_to(mut e protobuf.Encoder) {
	if m.path != '' {
		e.write_string_field(1, m.path)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &GetRequest) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn GetRequest.decode(buf []u8) !GetRequest {
	mut m := GetRequest{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.path = d.read_string()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &GetRequest) to_any() GoogleProtobuf_Any {
	return GoogleProtobuf_Any{
		type_url: 'type.googleapis.com/registry.GetRequest'
		value:    m.encode()
	}
}

pub fn GetRequest.from_any(a GoogleProtobuf_Any) !GetRequest {
	got := a.type_url.all_after_last('/')
	if got != 'registry.GetRequest' {
		return error('protobuf: Any holds `${got}`, not `registry.GetRequest`')
	}
	return GetRequest.decode(a.value)!
}

pub fn (m &GetRequest) json() !string {
	return m.json_value()!.json_str()
}

pub fn GetRequest.from_json(s string) !GetRequest {
	return GetRequest.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &GetRequest) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.path != '' {
		o['path'] = json2.Any(m.path)
	}
	return json2.Any(o)
}

pub fn GetRequest.from_json_value(a json2.Any) !GetRequest {
	obj := protobuf.json_object(a)!
	mut m := GetRequest{}
	for jk, jv in obj {
		match jk {
			'path' {
				if jv !is json2.Null {
					m.path = protobuf.json_stringv(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct GetResponse {
pub mut:
	node       ?Node
	found      bool
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &GetResponse) encoded_size() int {
	mut n := 0
	if node := m.node {
		n += protobuf.len_field_len(1, node.encoded_size())
	}
	if m.found {
		n += protobuf.tag_len(2) + 1
	}
	return n + m.pb_unknown.len
}

pub fn (m &GetResponse) encode_to(mut e protobuf.Encoder) {
	if node := m.node {
		e.write_tag(1, .len_delim)
		e.write_varint(u64(node.encoded_size()))
		node.encode_to(mut e)
	}
	if m.found {
		e.write_bool_field(2, m.found)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &GetResponse) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn GetResponse.decode(buf []u8) !GetResponse {
	mut m := GetResponse{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				mv_node := d.read_view()!
				mut mb_node := []u8{}
				if old := m.node {
					mb_node = old.encode()
				}
				mb_node << mv_node
				m.node = Node.decode(mb_node)!
			}
			2 {
				m.found = d.read_bool()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &GetResponse) to_any() GoogleProtobuf_Any {
	return GoogleProtobuf_Any{
		type_url: 'type.googleapis.com/registry.GetResponse'
		value:    m.encode()
	}
}

pub fn GetResponse.from_any(a GoogleProtobuf_Any) !GetResponse {
	got := a.type_url.all_after_last('/')
	if got != 'registry.GetResponse' {
		return error('protobuf: Any holds `${got}`, not `registry.GetResponse`')
	}
	return GetResponse.decode(a.value)!
}

pub fn (m &GetResponse) json() !string {
	return m.json_value()!.json_str()
}

pub fn GetResponse.from_json(s string) !GetResponse {
	return GetResponse.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &GetResponse) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if node := m.node {
		o['node'] = node.json_value()!
	}
	if m.found {
		o['found'] = json2.Any(m.found)
	}
	return json2.Any(o)
}

pub fn GetResponse.from_json_value(a json2.Any) !GetResponse {
	obj := protobuf.json_object(a)!
	mut m := GetResponse{}
	for jk, jv in obj {
		match jk {
			'node' {
				if jv !is json2.Null {
					m.node = Node.from_json_value(jv)!
				}
			}
			'found' {
				if jv !is json2.Null {
					m.found = protobuf.json_boolv(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct GoogleProtobuf_Timestamp {
pub mut:
	seconds    i64
	nanos      int
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &GoogleProtobuf_Timestamp) encoded_size() int {
	mut n := 0
	if m.seconds != 0 {
		n += protobuf.tag_len(1) + protobuf.varint_len(u64(m.seconds))
	}
	if m.nanos != 0 {
		n += protobuf.tag_len(2) + protobuf.varint_len(u64(i64(m.nanos)))
	}
	return n + m.pb_unknown.len
}

pub fn (m &GoogleProtobuf_Timestamp) encode_to(mut e protobuf.Encoder) {
	if m.seconds != 0 {
		e.write_int64_field(1, m.seconds)
	}
	if m.nanos != 0 {
		e.write_int32_field(2, m.nanos)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &GoogleProtobuf_Timestamp) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn GoogleProtobuf_Timestamp.decode(buf []u8) !GoogleProtobuf_Timestamp {
	mut m := GoogleProtobuf_Timestamp{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.seconds = d.read_int64()!
			}
			2 {
				m.nanos = d.read_int32()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

// as_time converts to time.Time (UTC); out-of-spec nanos are clamped
pub fn (m &GoogleProtobuf_Timestamp) as_time() time.Time {
	mut n := m.nanos
	if n < 0 {
		n = 0
	} else if n > 999_999_999 {
		n = 999_999_999
	}
	return time.unix_nanosecond(m.seconds, n)
}

pub fn GoogleProtobuf_Timestamp.from_time(t time.Time) GoogleProtobuf_Timestamp {
	return GoogleProtobuf_Timestamp{
		seconds: t.unix()
		nanos:   t.nanosecond
	}
}

pub fn (m &GoogleProtobuf_Timestamp) to_any() GoogleProtobuf_Any {
	return GoogleProtobuf_Any{
		type_url: 'type.googleapis.com/google.protobuf.Timestamp'
		value:    m.encode()
	}
}

pub fn GoogleProtobuf_Timestamp.from_any(a GoogleProtobuf_Any) !GoogleProtobuf_Timestamp {
	got := a.type_url.all_after_last('/')
	if got != 'google.protobuf.Timestamp' {
		return error('protobuf: Any holds `${got}`, not `google.protobuf.Timestamp`')
	}
	return GoogleProtobuf_Timestamp.decode(a.value)!
}

pub fn (m &GoogleProtobuf_Timestamp) json() !string {
	return m.json_value()!.json_str()
}

pub fn GoogleProtobuf_Timestamp.from_json(s string) !GoogleProtobuf_Timestamp {
	return GoogleProtobuf_Timestamp.from_json_value(protobuf.json_parse(s)!)
}

// canonical JSON form: RFC 3339 in UTC
pub fn (m &GoogleProtobuf_Timestamp) json_value() !json2.Any {
	// protojson range: 0001-01-01T00:00:00Z .. 9999-12-31T23:59:59.999999999Z
	if m.seconds < -62135596800 || m.seconds > 253402300799 || m.nanos < 0 || m.nanos > 999999999 {
		return error('protojson: timestamp out of range')
	}
	t := time.unix(m.seconds)
	mut frac := ''
	if m.nanos != 0 {
		if m.nanos % 1_000_000 == 0 {
			frac = '.${(m.nanos / 1_000_000):03d}'
		} else if m.nanos % 1_000 == 0 {
			frac = '.${(m.nanos / 1_000):06d}'
		} else {
			frac = '.${m.nanos:09d}'
		}
	}
	return json2.Any('${t.year:04d}-${t.month:02d}-${t.day:02d}T${t.hour:02d}:${t.minute:02d}:${t.second:02d}${frac}Z')
}

pub fn GoogleProtobuf_Timestamp.from_json_value(a json2.Any) !GoogleProtobuf_Timestamp {
	s := protobuf.json_stringv(a)!
	secs, nanos := protobuf.parse_timestamp_rfc3339(s)!
	return GoogleProtobuf_Timestamp{
		seconds: secs
		nanos:   nanos
	}
}

pub struct GoogleProtobuf_Duration {
pub mut:
	seconds    i64
	nanos      int
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &GoogleProtobuf_Duration) encoded_size() int {
	mut n := 0
	if m.seconds != 0 {
		n += protobuf.tag_len(1) + protobuf.varint_len(u64(m.seconds))
	}
	if m.nanos != 0 {
		n += protobuf.tag_len(2) + protobuf.varint_len(u64(i64(m.nanos)))
	}
	return n + m.pb_unknown.len
}

pub fn (m &GoogleProtobuf_Duration) encode_to(mut e protobuf.Encoder) {
	if m.seconds != 0 {
		e.write_int64_field(1, m.seconds)
	}
	if m.nanos != 0 {
		e.write_int32_field(2, m.nanos)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &GoogleProtobuf_Duration) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn GoogleProtobuf_Duration.decode(buf []u8) !GoogleProtobuf_Duration {
	mut m := GoogleProtobuf_Duration{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.seconds = d.read_int64()!
			}
			2 {
				m.nanos = d.read_int32()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

// as_duration saturates at the i64-nanosecond range (~±292 years),
// like protobuf-go — proto durations span ±10000 years
pub fn (m &GoogleProtobuf_Duration) as_duration() time.Duration {
	if m.seconds >= 9223372037 {
		return time.Duration(i64(9223372036854775807))
	}
	if m.seconds <= -9223372037 {
		return time.Duration(i64(-9223372036854775807) - 1)
	}
	secs_ns := m.seconds * 1_000_000_000
	if secs_ns > 0 && i64(m.nanos) > 9223372036854775807 - secs_ns {
		return time.Duration(i64(9223372036854775807))
	}
	if secs_ns < 0 && i64(m.nanos) < (i64(-9223372036854775807) - 1) - secs_ns {
		return time.Duration(i64(-9223372036854775807) - 1)
	}
	return time.Duration(secs_ns + i64(m.nanos))
}

pub fn GoogleProtobuf_Duration.from_duration(d time.Duration) GoogleProtobuf_Duration {
	return GoogleProtobuf_Duration{
		seconds: i64(d) / 1_000_000_000
		nanos:   int(i64(d) % 1_000_000_000)
	}
}

pub fn (m &GoogleProtobuf_Duration) to_any() GoogleProtobuf_Any {
	return GoogleProtobuf_Any{
		type_url: 'type.googleapis.com/google.protobuf.Duration'
		value:    m.encode()
	}
}

pub fn GoogleProtobuf_Duration.from_any(a GoogleProtobuf_Any) !GoogleProtobuf_Duration {
	got := a.type_url.all_after_last('/')
	if got != 'google.protobuf.Duration' {
		return error('protobuf: Any holds `${got}`, not `google.protobuf.Duration`')
	}
	return GoogleProtobuf_Duration.decode(a.value)!
}

pub fn (m &GoogleProtobuf_Duration) json() !string {
	return m.json_value()!.json_str()
}

pub fn GoogleProtobuf_Duration.from_json(s string) !GoogleProtobuf_Duration {
	return GoogleProtobuf_Duration.from_json_value(protobuf.json_parse(s)!)
}

// canonical JSON form: decimal seconds with an s suffix
pub fn (m &GoogleProtobuf_Duration) json_value() !json2.Any {
	// protojson range: |seconds| <= 315576000000, matching-sign nanos
	if m.seconds < -315576000000 || m.seconds > 315576000000 || m.nanos < -999999999
		|| m.nanos > 999999999 {
		return error('protojson: duration out of range')
	}
	if (m.seconds < 0 && m.nanos > 0) || (m.seconds > 0 && m.nanos < 0) {
		return error('protojson: duration sign mismatch')
	}
	mut s := m.seconds
	mut n := m.nanos
	neg := s < 0 || n < 0
	if s < 0 {
		s = -s
	}
	if n < 0 {
		n = -n
	}
	mut frac := ''
	if n != 0 {
		if n % 1_000_000 == 0 {
			frac = '.${(n / 1_000_000):03d}'
		} else if n % 1_000 == 0 {
			frac = '.${(n / 1_000):06d}'
		} else {
			frac = '.${n:09d}'
		}
	}
	sign := if neg { '-' } else { '' }
	return json2.Any('${sign}${s}${frac}s')
}

pub fn GoogleProtobuf_Duration.from_json_value(a json2.Any) !GoogleProtobuf_Duration {
	str := protobuf.json_stringv(a)!
	if !str.ends_with('s') || str.len < 2 {
		return error('protojson: bad duration `${str}`')
	}
	mut body := str[..str.len - 1]
	neg := body.starts_with('-')
	if neg {
		body = body[1..]
	}
	parts := body.split('.')
	if parts.len > 2 {
		return error('protojson: bad duration `${str}`')
	}
	mut secs := protobuf.json_key_i64(parts[0])!
	mut nanos := i64(0)
	if parts.len == 2 {
		if parts[1].len == 0 || parts[1].len > 9 {
			return error('protojson: bad duration `${str}`')
		}
		nanos = protobuf.json_key_i64(parts[1] + '0'.repeat(9 - parts[1].len))!
	}
	if neg {
		secs = -secs
		nanos = -nanos
	}
	return GoogleProtobuf_Duration{
		seconds: secs
		nanos:   int(nanos)
	}
}

pub struct GoogleProtobuf_Any {
pub mut:
	type_url   string
	value      []u8
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &GoogleProtobuf_Any) encoded_size() int {
	mut n := 0
	if m.type_url != '' {
		n += protobuf.len_field_len(1, m.type_url.len)
	}
	if m.value.len > 0 {
		n += protobuf.len_field_len(2, m.value.len)
	}
	return n + m.pb_unknown.len
}

pub fn (m &GoogleProtobuf_Any) encode_to(mut e protobuf.Encoder) {
	if m.type_url != '' {
		e.write_string_field(1, m.type_url)
	}
	if m.value.len > 0 {
		e.write_bytes_field(2, m.value)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &GoogleProtobuf_Any) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn GoogleProtobuf_Any.decode(buf []u8) !GoogleProtobuf_Any {
	mut m := GoogleProtobuf_Any{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.type_url = d.read_string()!
			}
			2 {
				m.value = d.read_bytes()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

// the packed message type name (the type_url after the last /)
pub fn (m &GoogleProtobuf_Any) type_name() string {
	return m.type_url.all_after_last('/')
}

pub fn (m &GoogleProtobuf_Any) to_any() GoogleProtobuf_Any {
	return GoogleProtobuf_Any{
		type_url: 'type.googleapis.com/google.protobuf.Any'
		value:    m.encode()
	}
}

pub fn GoogleProtobuf_Any.from_any(a GoogleProtobuf_Any) !GoogleProtobuf_Any {
	got := a.type_url.all_after_last('/')
	if got != 'google.protobuf.Any' {
		return error('protobuf: Any holds `${got}`, not `google.protobuf.Any`')
	}
	return GoogleProtobuf_Any.decode(a.value)!
}

pub fn (m &GoogleProtobuf_Any) json() !string {
	return m.json_value()!.json_str()
}

pub fn GoogleProtobuf_Any.from_json(s string) !GoogleProtobuf_Any {
	return GoogleProtobuf_Any.from_json_value(protobuf.json_parse(s)!)
}

// canonical JSON: {"@type": url, ...fields} for normal messages,
// {"@type": url, "value": <form>} for value-wrapped WKTs. Uses the
// generated fileset resolver; unresolvable types degrade to a raw
// base64 form rather than erroring (json_value cannot fail).
pub fn (m &GoogleProtobuf_Any) json_value() !json2.Any {
	if m.type_url == '' {
		return json2.Any(map[string]json2.Any{})
	}
	name := m.type_url.all_after_last('/')
	inner, wrapped := pb_any_to_json(name, m.value) or {
		mut raw := map[string]json2.Any{}
		raw['@type'] = json2.Any(m.type_url)
		raw['value'] = protobuf.json_b64(m.value)
		return json2.Any(raw)
	}
	mut o := map[string]json2.Any{}
	o['@type'] = json2.Any(m.type_url)
	if wrapped {
		o['value'] = inner
	} else if inner is map[string]json2.Any {
		for k, v in inner {
			o[k] = v
		}
	} else {
		o['value'] = inner
	}
	return json2.Any(o)
}

pub fn GoogleProtobuf_Any.from_json_value(a json2.Any) !GoogleProtobuf_Any {
	obj := protobuf.json_object(a)!
	if obj.len == 0 {
		return GoogleProtobuf_Any{}
	}
	tu := obj['@type'] or { return error('protojson: Any missing "@type"') }
	type_url := protobuf.json_stringv(tu)!
	name := type_url.all_after_last('/')
	value := pb_any_from_json(name, obj)!
	return GoogleProtobuf_Any{
		type_url: type_url
		value:    value
	}
}

fn pb_any_to_json(pb_name string, pb_value []u8) !(json2.Any, bool) {
	match pb_name {
		'registry.Node' {
			return Node.decode(pb_value)!.json_value()!, false
		}
		'registry.PutRequest' {
			return PutRequest.decode(pb_value)!.json_value()!, false
		}
		'registry.PutResponse' {
			return PutResponse.decode(pb_value)!.json_value()!, false
		}
		'registry.GetRequest' {
			return GetRequest.decode(pb_value)!.json_value()!, false
		}
		'registry.GetResponse' {
			return GetResponse.decode(pb_value)!.json_value()!, false
		}
		'google.protobuf.Timestamp' {
			return GoogleProtobuf_Timestamp.decode(pb_value)!.json_value()!, true
		}
		'google.protobuf.Duration' {
			return GoogleProtobuf_Duration.decode(pb_value)!.json_value()!, true
		}
		'google.protobuf.Any' {
			return GoogleProtobuf_Any.decode(pb_value)!.json_value()!, true
		}
		else {
			return error('protojson: unresolvable Any type `${pb_name}`')
		}
	}
}

fn pb_any_from_json(pb_name string, pb_obj map[string]json2.Any) ![]u8 {
	match pb_name {
		'registry.Node' {
			mut pb_inner := pb_obj.clone()
			pb_inner.delete('@type')
			return Node.from_json_value(json2.Any(pb_inner))!.encode()
		}
		'registry.PutRequest' {
			mut pb_inner := pb_obj.clone()
			pb_inner.delete('@type')
			return PutRequest.from_json_value(json2.Any(pb_inner))!.encode()
		}
		'registry.PutResponse' {
			mut pb_inner := pb_obj.clone()
			pb_inner.delete('@type')
			return PutResponse.from_json_value(json2.Any(pb_inner))!.encode()
		}
		'registry.GetRequest' {
			mut pb_inner := pb_obj.clone()
			pb_inner.delete('@type')
			return GetRequest.from_json_value(json2.Any(pb_inner))!.encode()
		}
		'registry.GetResponse' {
			mut pb_inner := pb_obj.clone()
			pb_inner.delete('@type')
			return GetResponse.from_json_value(json2.Any(pb_inner))!.encode()
		}
		'google.protobuf.Timestamp' {
			pb_v := pb_obj['value'] or {
				return error('protojson: Any of google.protobuf.Timestamp missing "value"')
			}
			return GoogleProtobuf_Timestamp.from_json_value(pb_v)!.encode()
		}
		'google.protobuf.Duration' {
			pb_v := pb_obj['value'] or {
				return error('protojson: Any of google.protobuf.Duration missing "value"')
			}
			return GoogleProtobuf_Duration.from_json_value(pb_v)!.encode()
		}
		'google.protobuf.Any' {
			pb_v := pb_obj['value'] or {
				return error('protojson: Any of google.protobuf.Any missing "value"')
			}
			return GoogleProtobuf_Any.from_json_value(pb_v)!.encode()
		}
		else {
			return error('protojson: unresolvable Any type `${pb_name}`')
		}
	}
}
