// Code generated by protobuf.gen. DO NOT EDIT.
module main

import grpc

pub struct RegistryClient {
pub mut:
	c grpc.Client
}

pub fn (mut x RegistryClient) put(req PutRequest, opts ...grpc.CallOption) !grpc.Reply[PutResponse] {
	raw := x.c.unary('/registry.Registry/Put', req.encode(), ...opts)!
	return grpc.Reply[PutResponse]{
		msg:      PutResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub fn (mut x RegistryClient) get(req GetRequest, opts ...grpc.CallOption) !grpc.Reply[GetResponse] {
	raw := x.c.unary('/registry.Registry/Get', req.encode(), ...opts)!
	return grpc.Reply[GetResponse]{
		msg:      GetResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub interface RegistryHandler {
mut:
	put(mut ctx grpc.ServerContext, req PutRequest) !PutResponse
	get(mut ctx grpc.ServerContext, req GetRequest) !GetResponse
}

pub struct RegistryService {
pub mut:
	h RegistryHandler
}

pub fn (mut s RegistryService) call(path string, codec grpc.Codec, body []u8, mut ctx grpc.ServerContext) !([]u8, bool) {
	match path {
		'/registry.Registry/Put' {
			req := if codec == .json {
				PutRequest.from_json(body.bytestr())!
			} else {
				PutRequest.decode(body)!
			}
			resp := s.h.put(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/registry.Registry/Get' {
			req := if codec == .json {
				GetRequest.from_json(body.bytestr())!
			} else {
				GetRequest.decode(body)!
			}
			resp := s.h.get(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		else {
			return []u8{}, false
		}
	}
}
