// the etcd-lite dogfood schema: unary get/put now, streaming scan later

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: kv.proto

package kvconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	kv "example.com/kvserver/kv"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// KVName is the fully-qualified name of the KV service.
	KVName = "kv.KV"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// KVGetProcedure is the fully-qualified name of the KV's Get RPC.
	KVGetProcedure = "/kv.KV/Get"
	// KVPutProcedure is the fully-qualified name of the KV's Put RPC.
	KVPutProcedure = "/kv.KV/Put"
	// KVScanProcedure is the fully-qualified name of the KV's Scan RPC.
	KVScanProcedure = "/kv.KV/Scan"
)

// KVClient is a client for the kv.KV service.
type KVClient interface {
	Get(context.Context, *connect.Request[kv.GetRequest]) (*connect.Response[kv.GetResponse], error)
	Put(context.Context, *connect.Request[kv.PutRequest]) (*connect.Response[kv.PutResponse], error)
	Scan(context.Context, *connect.Request[kv.GetRequest]) (*connect.ServerStreamForClient[kv.GetResponse], error)
}

// NewKVClient constructs a client for the kv.KV service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewKVClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) KVClient {
	baseURL = strings.TrimRight(baseURL, "/")
	kVMethods := kv.File_kv_proto.Services().ByName("KV").Methods()
	return &kVClient{
		get: connect.NewClient[kv.GetRequest, kv.GetResponse](
			httpClient,
			baseURL+KVGetProcedure,
			connect.WithSchema(kVMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		put: connect.NewClient[kv.PutRequest, kv.PutResponse](
			httpClient,
			baseURL+KVPutProcedure,
			connect.WithSchema(kVMethods.ByName("Put")),
			connect.WithClientOptions(opts...),
		),
		scan: connect.NewClient[kv.GetRequest, kv.GetResponse](
			httpClient,
			baseURL+KVScanProcedure,
			connect.WithSchema(kVMethods.ByName("Scan")),
			connect.WithClientOptions(opts...),
		),
	}
}

// kVClient implements KVClient.
type kVClient struct {
	get  *connect.Client[kv.GetRequest, kv.GetResponse]
	put  *connect.Client[kv.PutRequest, kv.PutResponse]
	scan *connect.Client[kv.GetRequest, kv.GetResponse]
}

// Get calls kv.KV.Get.
func (c *kVClient) Get(ctx context.Context, req *connect.Request[kv.GetRequest]) (*connect.Response[kv.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Put calls kv.KV.Put.
func (c *kVClient) Put(ctx context.Context, req *connect.Request[kv.PutRequest]) (*connect.Response[kv.PutResponse], error) {
	return c.put.CallUnary(ctx, req)
}

// Scan calls kv.KV.Scan.
func (c *kVClient) Scan(ctx context.Context, req *connect.Request[kv.GetRequest]) (*connect.ServerStreamForClient[kv.GetResponse], error) {
	return c.scan.CallServerStream(ctx, req)
}

// KVHandler is an implementation of the kv.KV service.
type KVHandler interface {
	Get(context.Context, *connect.Request[kv.GetRequest]) (*connect.Response[kv.GetResponse], error)
	Put(context.Context, *connect.Request[kv.PutRequest]) (*connect.Response[kv.PutResponse], error)
	Scan(context.Context, *connect.Request[kv.GetRequest], *connect.ServerStream[kv.GetResponse]) error
}

// NewKVHandler builds an HTTP handler from the service implementation. It returns the path on which
// to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewKVHandler(svc KVHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	kVMethods := kv.File_kv_proto.Services().ByName("KV").Methods()
	kVGetHandler := connect.NewUnaryHandler(
		KVGetProcedure,
		svc.Get,
		connect.WithSchema(kVMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	kVPutHandler := connect.NewUnaryHandler(
		KVPutProcedure,
		svc.Put,
		connect.WithSchema(kVMethods.ByName("Put")),
		connect.WithHandlerOptions(opts...),
	)
	kVScanHandler := connect.NewServerStreamHandler(
		KVScanProcedure,
		svc.Scan,
		connect.WithSchema(kVMethods.ByName("Scan")),
		connect.WithHandlerOptions(opts...),
	)
	return "/kv.KV/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case KVGetProcedure:
			kVGetHandler.ServeHTTP(w, r)
		case KVPutProcedure:
			kVPutHandler.ServeHTTP(w, r)
		case KVScanProcedure:
			kVScanHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedKVHandler returns CodeUnimplemented from all methods.
type UnimplementedKVHandler struct{}

func (UnimplementedKVHandler) Get(context.Context, *connect.Request[kv.GetRequest]) (*connect.Response[kv.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kv.KV.Get is not implemented"))
}

func (UnimplementedKVHandler) Put(context.Context, *connect.Request[kv.PutRequest]) (*connect.Response[kv.PutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kv.KV.Put is not implemented"))
}

func (UnimplementedKVHandler) Scan(context.Context, *connect.Request[kv.GetRequest], *connect.ServerStream[kv.GetResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("kv.KV.Scan is not implemented"))
}
