// Code generated by protobuf.gen. DO NOT EDIT.
module main

import grpc

pub struct KVClient {
pub mut:
	c grpc.Client
}

pub fn (mut x KVClient) get(req GetRequest) !GetResponse {
	resp := x.c.unary('/kv.KV/Get', req.encode())!
	return GetResponse.decode(resp)!
}

pub fn (mut x KVClient) put(req PutRequest) !PutResponse {
	resp := x.c.unary('/kv.KV/Put', req.encode())!
	return PutResponse.decode(resp)!
}

// rpc Scan skipped: server streaming is not supported yet
