// Code generated by protobuf.gen. DO NOT EDIT.
module main

import grpc

pub struct KVClient {
pub mut:
	c grpc.Client
}

pub fn (mut x KVClient) get(req GetRequest, opts ...grpc.CallOption) !grpc.Reply[GetResponse] {
	raw := x.c.unary('/kv.KV/Get', req.encode(), ...opts)!
	return grpc.Reply[GetResponse]{
		msg:      GetResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub fn (mut x KVClient) put(req PutRequest, opts ...grpc.CallOption) !grpc.Reply[PutResponse] {
	raw := x.c.unary('/kv.KV/Put', req.encode(), ...opts)!
	return grpc.Reply[PutResponse]{
		msg:      PutResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub fn (mut x KVClient) scan(req GetRequest, opts ...grpc.CallOption) !grpc.Reply[[]GetResponse] {
	raw := x.c.server_stream('/kv.KV/Scan', req.encode(), ...opts)!
	mut msgs := []GetResponse{cap: raw.payloads.len}
	for p in raw.payloads {
		msgs << GetResponse.decode(p)!
	}
	return grpc.Reply[[]GetResponse]{
		msg:      msgs
		metadata: raw.metadata
	}
}

pub fn (mut x KVClient) put_many(reqs []PutRequest, opts ...grpc.CallOption) !grpc.Reply[PutManyResponse] {
	mut bodies := [][]u8{cap: reqs.len}
	for r in reqs {
		bodies << r.encode()
	}
	raw := x.c.client_stream('/kv.KV/PutMany', bodies, ...opts)!
	return grpc.Reply[PutManyResponse]{
		msg:      PutManyResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub interface KVHandler {
mut:
	get(mut ctx grpc.ServerContext, req GetRequest) !GetResponse
	put(mut ctx grpc.ServerContext, req PutRequest) !PutResponse
	scan(mut ctx grpc.ServerContext, req GetRequest) ![]GetResponse
	put_many(mut ctx grpc.ServerContext, reqs []PutRequest) !PutManyResponse
}

pub struct KVService {
pub mut:
	h KVHandler
}

pub fn (mut s KVService) call(path string, codec grpc.Codec, body []u8, mut ctx grpc.ServerContext) !([]u8, bool) {
	match path {
		'/kv.KV/Get' {
			req := if codec == .json {
				GetRequest.from_json(body.bytestr())!
			} else {
				GetRequest.decode(body)!
			}
			resp := s.h.get(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/kv.KV/Put' {
			req := if codec == .json {
				PutRequest.from_json(body.bytestr())!
			} else {
				PutRequest.decode(body)!
			}
			resp := s.h.put(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		else {
			return []u8{}, false
		}
	}
}

pub fn (mut s KVService) grpc_call(path string, reqs [][]u8, mut ctx grpc.ServerContext) !([][]u8, bool) {
	match path {
		'/kv.KV/Get' {
			if reqs.len != 1 {
				return grpc.StatusError{
					status: grpc.Status{
						code:    .invalid_argument
						message: 'Get expects exactly one request message'
					}
				}
			}
			req := GetRequest.decode(reqs[0])!
			resp := s.h.get(mut ctx, req)!
			return [resp.encode()], true
		}
		'/kv.KV/Put' {
			if reqs.len != 1 {
				return grpc.StatusError{
					status: grpc.Status{
						code:    .invalid_argument
						message: 'Put expects exactly one request message'
					}
				}
			}
			req := PutRequest.decode(reqs[0])!
			resp := s.h.put(mut ctx, req)!
			return [resp.encode()], true
		}
		'/kv.KV/Scan' {
			if reqs.len != 1 {
				return grpc.StatusError{
					status: grpc.Status{
						code:    .invalid_argument
						message: 'Scan expects exactly one request message'
					}
				}
			}
			req := GetRequest.decode(reqs[0])!
			resps := s.h.scan(mut ctx, req)!
			mut out := [][]u8{cap: resps.len}
			for r in resps {
				out << r.encode()
			}
			return out, true
		}
		'/kv.KV/PutMany' {
			mut msgs := []PutRequest{cap: reqs.len}
			for b_ in reqs {
				msgs << PutRequest.decode(b_)!
			}
			resp := s.h.put_many(mut ctx, msgs)!
			return [resp.encode()], true
		}
		else {
			return [][]u8{}, false
		}
	}
}
