// Code generated by protobuf.gen. DO NOT EDIT.
module main

import grpc

pub struct KVClient {
pub mut:
	c grpc.Client
}

pub fn (mut x KVClient) get(req GetRequest, opts ...grpc.CallOption) !grpc.Reply[GetResponse] {
	raw := x.c.unary('/kv.KV/Get', req.encode(), ...opts)!
	return grpc.Reply[GetResponse]{
		msg:      GetResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub fn (mut x KVClient) put(req PutRequest, opts ...grpc.CallOption) !grpc.Reply[PutResponse] {
	raw := x.c.unary('/kv.KV/Put', req.encode(), ...opts)!
	return grpc.Reply[PutResponse]{
		msg:      PutResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

// rpc Scan skipped: server streaming is not supported yet

pub interface KVHandler {
mut:
	get(mut ctx grpc.ServerContext, req GetRequest) !GetResponse
	put(mut ctx grpc.ServerContext, req PutRequest) !PutResponse
}

pub struct KVService {
pub mut:
	h KVHandler
}

pub fn (mut s KVService) call(path string, codec grpc.Codec, body []u8, mut ctx grpc.ServerContext) !([]u8, bool) {
	match path {
		'/kv.KV/Get' {
			req := if codec == .json {
				GetRequest.from_json(body.bytestr())!
			} else {
				GetRequest.decode(body)!
			}
			resp := s.h.get(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/kv.KV/Put' {
			req := if codec == .json {
				PutRequest.from_json(body.bytestr())!
			} else {
				PutRequest.decode(body)!
			}
			resp := s.h.put(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		else {
			return []u8{}, false
		}
	}
}
