// Code generated by protobuf.gen. DO NOT EDIT.
module main

import json2
import protobuf

pub struct GetRequest {
pub mut:
	key        string
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &GetRequest) encoded_size() int {
	mut n := 0
	if m.key != '' {
		n += protobuf.len_field_len(1, m.key.len)
	}
	return n + m.pb_unknown.len
}

pub fn (m &GetRequest) encode_to(mut e protobuf.Encoder) {
	if m.key != '' {
		e.write_string_field(1, m.key)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &GetRequest) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn GetRequest.decode(buf []u8) !GetRequest {
	mut m := GetRequest{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.key = d.read_string()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &GetRequest) json() !string {
	return m.json_value()!.json_str()
}

pub fn GetRequest.from_json(s string) !GetRequest {
	return GetRequest.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &GetRequest) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.key != '' {
		o['key'] = json2.Any(m.key)
	}
	return json2.Any(o)
}

pub fn GetRequest.from_json_value(a json2.Any) !GetRequest {
	obj := protobuf.json_object(a)!
	mut m := GetRequest{}
	for jk, jv in obj {
		match jk {
			'key' {
				if jv !is json2.Null {
					m.key = protobuf.json_stringv(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct GetResponse {
pub mut:
	value      []u8
	found      bool
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &GetResponse) encoded_size() int {
	mut n := 0
	if m.value.len > 0 {
		n += protobuf.len_field_len(1, m.value.len)
	}
	if m.found {
		n += protobuf.tag_len(2) + 1
	}
	return n + m.pb_unknown.len
}

pub fn (m &GetResponse) encode_to(mut e protobuf.Encoder) {
	if m.value.len > 0 {
		e.write_bytes_field(1, m.value)
	}
	if m.found {
		e.write_bool_field(2, m.found)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &GetResponse) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn GetResponse.decode(buf []u8) !GetResponse {
	mut m := GetResponse{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.value = d.read_bytes()!
			}
			2 {
				m.found = d.read_bool()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &GetResponse) json() !string {
	return m.json_value()!.json_str()
}

pub fn GetResponse.from_json(s string) !GetResponse {
	return GetResponse.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &GetResponse) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.value.len > 0 {
		o['value'] = protobuf.json_b64(m.value)
	}
	if m.found {
		o['found'] = json2.Any(m.found)
	}
	return json2.Any(o)
}

pub fn GetResponse.from_json_value(a json2.Any) !GetResponse {
	obj := protobuf.json_object(a)!
	mut m := GetResponse{}
	for jk, jv in obj {
		match jk {
			'value' {
				if jv !is json2.Null {
					m.value = protobuf.json_bytesv(jv)!
				}
			}
			'found' {
				if jv !is json2.Null {
					m.found = protobuf.json_boolv(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct PutRequest {
pub mut:
	key        string
	value      []u8
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &PutRequest) encoded_size() int {
	mut n := 0
	if m.key != '' {
		n += protobuf.len_field_len(1, m.key.len)
	}
	if m.value.len > 0 {
		n += protobuf.len_field_len(2, m.value.len)
	}
	return n + m.pb_unknown.len
}

pub fn (m &PutRequest) encode_to(mut e protobuf.Encoder) {
	if m.key != '' {
		e.write_string_field(1, m.key)
	}
	if m.value.len > 0 {
		e.write_bytes_field(2, m.value)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &PutRequest) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn PutRequest.decode(buf []u8) !PutRequest {
	mut m := PutRequest{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.key = d.read_string()!
			}
			2 {
				m.value = d.read_bytes()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &PutRequest) json() !string {
	return m.json_value()!.json_str()
}

pub fn PutRequest.from_json(s string) !PutRequest {
	return PutRequest.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &PutRequest) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.key != '' {
		o['key'] = json2.Any(m.key)
	}
	if m.value.len > 0 {
		o['value'] = protobuf.json_b64(m.value)
	}
	return json2.Any(o)
}

pub fn PutRequest.from_json_value(a json2.Any) !PutRequest {
	obj := protobuf.json_object(a)!
	mut m := PutRequest{}
	for jk, jv in obj {
		match jk {
			'key' {
				if jv !is json2.Null {
					m.key = protobuf.json_stringv(jv)!
				}
			}
			'value' {
				if jv !is json2.Null {
					m.value = protobuf.json_bytesv(jv)!
				}
			}
			else {}
		}
	}
	return m
}

pub struct PutResponse {
pub mut:
	replaced   bool
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &PutResponse) encoded_size() int {
	mut n := 0
	if m.replaced {
		n += protobuf.tag_len(1) + 1
	}
	return n + m.pb_unknown.len
}

pub fn (m &PutResponse) encode_to(mut e protobuf.Encoder) {
	if m.replaced {
		e.write_bool_field(1, m.replaced)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &PutResponse) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn PutResponse.decode(buf []u8) !PutResponse {
	mut m := PutResponse{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.replaced = d.read_bool()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &PutResponse) json() !string {
	return m.json_value()!.json_str()
}

pub fn PutResponse.from_json(s string) !PutResponse {
	return PutResponse.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &PutResponse) json_value() !json2.Any {
	mut o := map[string]json2.Any{}
	if m.replaced {
		o['replaced'] = json2.Any(m.replaced)
	}
	return json2.Any(o)
}

pub fn PutResponse.from_json_value(a json2.Any) !PutResponse {
	obj := protobuf.json_object(a)!
	mut m := PutResponse{}
	for jk, jv in obj {
		match jk {
			'replaced' {
				if jv !is json2.Null {
					m.replaced = protobuf.json_boolv(jv)!
				}
			}
			else {}
		}
	}
	return m
}
