// Code generated by protobuf.gen. DO NOT EDIT.
module main

import protobuf

pub struct GetRequest {
pub mut:
	key string
}

pub fn (m &GetRequest) encoded_size() int {
	mut n := 0
	if m.key != '' {
		n += protobuf.len_field_len(1, m.key.len)
	}
	return n
}

pub fn (m &GetRequest) encode_to(mut e protobuf.Encoder) {
	if m.key != '' {
		e.write_string_field(1, m.key)
	}
}

pub fn (m &GetRequest) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn GetRequest.decode(buf []u8) !GetRequest {
	mut m := GetRequest{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		field, wt := d.read_tag()!
		match field {
			1 {
				m.key = d.read_string()!
			}
			else {
				d.skip(wt)!
			}
		}
	}
	return m
}

pub struct GetResponse {
pub mut:
	value []u8
	found bool
}

pub fn (m &GetResponse) encoded_size() int {
	mut n := 0
	if m.value.len > 0 {
		n += protobuf.len_field_len(1, m.value.len)
	}
	if m.found {
		n += protobuf.tag_len(2) + 1
	}
	return n
}

pub fn (m &GetResponse) encode_to(mut e protobuf.Encoder) {
	if m.value.len > 0 {
		e.write_bytes_field(1, m.value)
	}
	if m.found {
		e.write_bool_field(2, m.found)
	}
}

pub fn (m &GetResponse) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn GetResponse.decode(buf []u8) !GetResponse {
	mut m := GetResponse{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		field, wt := d.read_tag()!
		match field {
			1 {
				m.value = d.read_bytes()!
			}
			2 {
				m.found = d.read_bool()!
			}
			else {
				d.skip(wt)!
			}
		}
	}
	return m
}

pub struct PutRequest {
pub mut:
	key   string
	value []u8
}

pub fn (m &PutRequest) encoded_size() int {
	mut n := 0
	if m.key != '' {
		n += protobuf.len_field_len(1, m.key.len)
	}
	if m.value.len > 0 {
		n += protobuf.len_field_len(2, m.value.len)
	}
	return n
}

pub fn (m &PutRequest) encode_to(mut e protobuf.Encoder) {
	if m.key != '' {
		e.write_string_field(1, m.key)
	}
	if m.value.len > 0 {
		e.write_bytes_field(2, m.value)
	}
}

pub fn (m &PutRequest) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn PutRequest.decode(buf []u8) !PutRequest {
	mut m := PutRequest{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		field, wt := d.read_tag()!
		match field {
			1 {
				m.key = d.read_string()!
			}
			2 {
				m.value = d.read_bytes()!
			}
			else {
				d.skip(wt)!
			}
		}
	}
	return m
}

pub struct PutResponse {
pub mut:
	replaced bool
}

pub fn (m &PutResponse) encoded_size() int {
	mut n := 0
	if m.replaced {
		n += protobuf.tag_len(1) + 1
	}
	return n
}

pub fn (m &PutResponse) encode_to(mut e protobuf.Encoder) {
	if m.replaced {
		e.write_bool_field(1, m.replaced)
	}
}

pub fn (m &PutResponse) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn PutResponse.decode(buf []u8) !PutResponse {
	mut m := PutResponse{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		field, wt := d.read_tag()!
		match field {
			1 {
				m.replaced = d.read_bool()!
			}
			else {
				d.skip(wt)!
			}
		}
	}
	return m
}
