// Code generated by protobuf.gen. DO NOT EDIT.
module main

import grpc

pub struct ConformanceServiceClient {
pub mut:
	c grpc.Client
}

pub fn (mut x ConformanceServiceClient) unary(req UnaryRequest, opts ...grpc.CallOption) !grpc.Reply[UnaryResponse] {
	raw := x.c.unary('/connectrpc.conformance.v1.ConformanceService/Unary', req.encode(), ...opts)!
	return grpc.Reply[UnaryResponse]{
		msg:      UnaryResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub fn (mut x ConformanceServiceClient) server_stream(req ServerStreamRequest, opts ...grpc.CallOption) !grpc.Reply[[]ServerStreamResponse] {
	raw := x.c.server_stream('/connectrpc.conformance.v1.ConformanceService/ServerStream',
		req.encode(), ...opts)!
	mut msgs := []ServerStreamResponse{cap: raw.payloads.len}
	for p in raw.payloads {
		msgs << ServerStreamResponse.decode(p)!
	}
	return grpc.Reply[[]ServerStreamResponse]{
		msg:      msgs
		metadata: raw.metadata
	}
}

pub fn (mut x ConformanceServiceClient) client_stream(reqs []ClientStreamRequest, opts ...grpc.CallOption) !grpc.Reply[ClientStreamResponse] {
	mut bodies := [][]u8{cap: reqs.len}
	for r in reqs {
		bodies << r.encode()
	}
	raw := x.c.client_stream('/connectrpc.conformance.v1.ConformanceService/ClientStream', bodies,
		...opts)!
	return grpc.Reply[ClientStreamResponse]{
		msg:      ClientStreamResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

// rpc BidiStream skipped: bidirectional streaming is not supported yet

pub fn (mut x ConformanceServiceClient) unimplemented(req UnimplementedRequest, opts ...grpc.CallOption) !grpc.Reply[UnimplementedResponse] {
	raw := x.c.unary('/connectrpc.conformance.v1.ConformanceService/Unimplemented', req.encode(),
		...opts)!
	return grpc.Reply[UnimplementedResponse]{
		msg:      UnimplementedResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub fn (mut x ConformanceServiceClient) idempotent_unary(req IdempotentUnaryRequest, opts ...grpc.CallOption) !grpc.Reply[IdempotentUnaryResponse] {
	raw := x.c.unary('/connectrpc.conformance.v1.ConformanceService/IdempotentUnary', req.encode(),
		...opts)!
	return grpc.Reply[IdempotentUnaryResponse]{
		msg:      IdempotentUnaryResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub interface ConformanceServiceHandler {
mut:
	unary(mut ctx grpc.ServerContext, req UnaryRequest) !UnaryResponse
	server_stream(mut ctx grpc.ServerContext, req ServerStreamRequest) ![]ServerStreamResponse
	client_stream(mut ctx grpc.ServerContext, reqs []ClientStreamRequest) !ClientStreamResponse
	unimplemented(mut ctx grpc.ServerContext, req UnimplementedRequest) !UnimplementedResponse
	idempotent_unary(mut ctx grpc.ServerContext, req IdempotentUnaryRequest) !IdempotentUnaryResponse
}

pub struct ConformanceServiceService {
pub mut:
	h ConformanceServiceHandler
}

pub fn (mut s ConformanceServiceService) call(path string, codec grpc.Codec, body []u8, mut ctx grpc.ServerContext) !([]u8, bool) {
	match path {
		'/connectrpc.conformance.v1.ConformanceService/Unary' {
			req := if codec == .json {
				UnaryRequest.from_json(body.bytestr())!
			} else {
				UnaryRequest.decode(body)!
			}
			resp := s.h.unary(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/connectrpc.conformance.v1.ConformanceService/Unimplemented' {
			req := if codec == .json {
				UnimplementedRequest.from_json(body.bytestr())!
			} else {
				UnimplementedRequest.decode(body)!
			}
			resp := s.h.unimplemented(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/connectrpc.conformance.v1.ConformanceService/IdempotentUnary' {
			req := if codec == .json {
				IdempotentUnaryRequest.from_json(body.bytestr())!
			} else {
				IdempotentUnaryRequest.decode(body)!
			}
			resp := s.h.idempotent_unary(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		else {
			return []u8{}, false
		}
	}
}

pub fn (mut s ConformanceServiceService) grpc_call(path string, reqs [][]u8, mut ctx grpc.ServerContext) !([][]u8, bool) {
	match path {
		'/connectrpc.conformance.v1.ConformanceService/Unary' {
			if reqs.len != 1 {
				return grpc.StatusError{
					status: grpc.Status{
						code:    .invalid_argument
						message: 'Unary expects exactly one request message'
					}
				}
			}
			req := UnaryRequest.decode(reqs[0])!
			resp := s.h.unary(mut ctx, req)!
			return [resp.encode()], true
		}
		'/connectrpc.conformance.v1.ConformanceService/ServerStream' {
			if reqs.len != 1 {
				return grpc.StatusError{
					status: grpc.Status{
						code:    .invalid_argument
						message: 'ServerStream expects exactly one request message'
					}
				}
			}
			req := ServerStreamRequest.decode(reqs[0])!
			resps := s.h.server_stream(mut ctx, req)!
			mut out := [][]u8{cap: resps.len}
			for r in resps {
				out << r.encode()
			}
			return out, true
		}
		'/connectrpc.conformance.v1.ConformanceService/ClientStream' {
			mut msgs := []ClientStreamRequest{cap: reqs.len}
			for b_ in reqs {
				msgs << ClientStreamRequest.decode(b_)!
			}
			resp := s.h.client_stream(mut ctx, msgs)!
			return [resp.encode()], true
		}
		'/connectrpc.conformance.v1.ConformanceService/Unimplemented' {
			if reqs.len != 1 {
				return grpc.StatusError{
					status: grpc.Status{
						code:    .invalid_argument
						message: 'Unimplemented expects exactly one request message'
					}
				}
			}
			req := UnimplementedRequest.decode(reqs[0])!
			resp := s.h.unimplemented(mut ctx, req)!
			return [resp.encode()], true
		}
		'/connectrpc.conformance.v1.ConformanceService/IdempotentUnary' {
			if reqs.len != 1 {
				return grpc.StatusError{
					status: grpc.Status{
						code:    .invalid_argument
						message: 'IdempotentUnary expects exactly one request message'
					}
				}
			}
			req := IdempotentUnaryRequest.decode(reqs[0])!
			resp := s.h.idempotent_unary(mut ctx, req)!
			return [resp.encode()], true
		}
		else {
			return [][]u8{}, false
		}
	}
}
