// Code generated by protobuf.gen. DO NOT EDIT.
module main

import grpc

pub struct ConformanceServiceClient {
pub mut:
	c grpc.Client
}

pub fn (mut x ConformanceServiceClient) unary(req UnaryRequest, opts ...grpc.CallOption) !grpc.Reply[UnaryResponse] {
	raw := x.c.unary('/connectrpc.conformance.v1.ConformanceService/Unary', req.encode(), ...opts)!
	return grpc.Reply[UnaryResponse]{
		msg:      UnaryResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

// rpc ServerStream skipped: server streaming is not supported yet

// rpc ClientStream skipped: client streaming is not supported yet

// rpc BidiStream skipped: bidirectional streaming is not supported yet

pub fn (mut x ConformanceServiceClient) unimplemented(req UnimplementedRequest, opts ...grpc.CallOption) !grpc.Reply[UnimplementedResponse] {
	raw := x.c.unary('/connectrpc.conformance.v1.ConformanceService/Unimplemented', req.encode(),
		...opts)!
	return grpc.Reply[UnimplementedResponse]{
		msg:      UnimplementedResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub fn (mut x ConformanceServiceClient) idempotent_unary(req IdempotentUnaryRequest, opts ...grpc.CallOption) !grpc.Reply[IdempotentUnaryResponse] {
	raw := x.c.unary('/connectrpc.conformance.v1.ConformanceService/IdempotentUnary', req.encode(),
		...opts)!
	return grpc.Reply[IdempotentUnaryResponse]{
		msg:      IdempotentUnaryResponse.decode(raw.payload)!
		metadata: raw.metadata
	}
}

pub interface ConformanceServiceHandler {
mut:
	unary(mut ctx grpc.ServerContext, req UnaryRequest) !UnaryResponse
	unimplemented(mut ctx grpc.ServerContext, req UnimplementedRequest) !UnimplementedResponse
	idempotent_unary(mut ctx grpc.ServerContext, req IdempotentUnaryRequest) !IdempotentUnaryResponse
}

pub struct ConformanceServiceService {
pub mut:
	h ConformanceServiceHandler
}

pub fn (mut s ConformanceServiceService) call(path string, codec grpc.Codec, body []u8, mut ctx grpc.ServerContext) !([]u8, bool) {
	match path {
		'/connectrpc.conformance.v1.ConformanceService/Unary' {
			req := if codec == .json {
				UnaryRequest.from_json(body.bytestr())!
			} else {
				UnaryRequest.decode(body)!
			}
			resp := s.h.unary(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/connectrpc.conformance.v1.ConformanceService/Unimplemented' {
			req := if codec == .json {
				UnimplementedRequest.from_json(body.bytestr())!
			} else {
				UnimplementedRequest.decode(body)!
			}
			resp := s.h.unimplemented(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		'/connectrpc.conformance.v1.ConformanceService/IdempotentUnary' {
			req := if codec == .json {
				IdempotentUnaryRequest.from_json(body.bytestr())!
			} else {
				IdempotentUnaryRequest.decode(body)!
			}
			resp := s.h.idempotent_unary(mut ctx, req)!
			out := if codec == .json {
				resp.json()!.bytes()
			} else {
				resp.encode()
			}
			return out, true
		}
		else {
			return []u8{}, false
		}
	}
}
